install.packages('remotes', repos='https://cloud.R-project.org')
remotes::install_version('jsonlite', version='1.6.0', repos='https://cloud.R-project.org')
remotes::install_version('devtools', version='2.3.2', repos='https://cloud.R-project.org')
remotes::install_version('jsonvalidate', version='1.1.0', repos='https://cloud.R-project.org')
remotes::install_version('RCurl', version='1.98.1.3', repos='https://cloud.R-project.org')
remotes::install_version('httr', version='1.4.2', repos='https://cloud.R-project.org')
remotes::install_version('uuid', version='0.1.4', repos='https://cloud.R-project.org')
remotes::install_version('paws', version='0.1.9', repos='https://cloud.R-project.org')
remotes::install_version('githubinstall', version='0.2.2', repos='https://cloud.R-project.org')
